build:
  version: "1.O"

accounts:
  message: "Welcome to EasyBank accounts related prod APIs"
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}f0ae087f8e45284c96448745485f7227ef8fb429afcb785bbb1bc4c3f8570c9ff19ab5009553bba110661a80e3675f83"
#    email: "aishwarya@easybank.com"
  onCallSupport:
    -(453)392-4829
    -(236)203-0384
