build:
  version: "3.O"

accounts:
  message: "Welcome to EasyBank accounts related local APIs"
  contactDetails:
    name: "John Deo - Developer"
    email: "john@easybank.com"
  onCallSupport:
    -(555)555-1234
    -(555)523-1345
