build:
  version: "2.O"

cards:
  message: "Welcome to EasyBank cards related local APIs"
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherryl@easyBank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267
