build:
  version: "1.O"

cards:
  message: "Welcome to EasyBank cards related docker APIs"
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@easybank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721













