build:
  version: "1.O"

loan:
  message: "Welcome to EasyBank loan related prod APIs"
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "pelias@easybank.com"
  onCallSupport:
    - (723) 656-8709

    - (156) 342-0956
