build:
  version: "2.O"

loan:
  message: "Welcome to EasyBanl loan related QA APIs"
  contactDetails:
    name: "Cyrano Marita - QA Lead"
    email: "cyrano@easybank.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467