build:
  version: "3.O"

loan:
  message: "Welcome to EasyBank loan related local APIs"
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@easybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934
